version: 2

models:
  - name: dvf
    columns:
      - name: id
        tests:
          - not_null
          - unique

      - name: date_mutation
        tests:
          - not_null

      - name: code_departement
        tests:
          - not_null

      - name: code_commune
        tests:
          - not_null

      - name: libelle_commune
        tests:
          - not_null

      - name: code_postal
        tests:
          - dbt_utils.expression_is_true:
              arguments:
                expression: "~ '^[0-9]{5}$'"
              config:
                where: "code_postal is not null"

      - name: code_insee
        tests:
          - not_null

      - name: annee
        tests:
          - not_null

      - name: load_date
        tests:
          - not_null
        
      - name: nature_mutation
        test:
          - accepted_values:
              values:
                - Vente
                - "Vente en l'état futur d'achèvement"
                - "Vente terrain à batir"
                - Echange
                - Expropriation
                - Adjudication

      - name: type_local
        test:
          - accepted_values :
              values:
                - Appartement
                - Maison
                - Dépendance
                - "Local industriel. commercial ou assimilé"